#!/bin/bash

#sisestatakse arv ja selle numbrite summa arvutatakse
echo "siseast arv"
read arv
arv1=$arv
summa=0
while [ $arv -ne 0 ]

do
	jaak=$(($arv % 10))
	summa=$(($summa + $jaak))
	arv=$((arv / 10))
done
echo "Arv $arv1 numbrite summa on $summa"
